### ISSUE TITLE
i can׳t change image after i uploaded one

### ISSUE THREAD

**Issue by roysG** [rendro/vintageJS#27]
Hi,
i am trying to change image twice, but when i click on some effect i get the previous image(before i made the changed).
i am using through jquery.

second thing, i have few images that needs to get the effect, but it work only for one image, even if i define it for another variable.

**Comment by roysG** [comment]
any response ?

**Comment by roysG** [comment]
???

**Comment by rendro** [comment]
Regarding your first question:

You need to call `apply` in between to make the second effect to be applied on top of the first one. You can check vintagejs.com to see that it works to change the applied effect. vintagejs.com uses the latest version of this plugin.

Regarding your second question:
Can you give me some more information on how you try this. If you visit http://rendro.github.io/vintageJS/ you see that it is possible to apply effects to different images. Looks like it is an issue with your implementation rather than the plugin isself.

**Comment by roysG** [comment]
Thanks for your redsponse, if fixed the problem
