### ISSUE TITLE
VintageJS is not defined

### ISSUE THREAD

**Issue by hvadotnarola** [rendro/vintageJS#36]
While implementing with ionic 1 and ionic modal, its giving error like 
`ReferenceError: VintageJS is not defined`

How can i overcome this ?

**Comment by rendro** [comment]
If you are using the latest version (2.0.0 or higher) the exported variable should be `vintageJS` not `VintageJS` because it's only a function, not a constructor.

Take a look at the  (example)[https://github.com/rendro/vintageJS/blob/master/examples/example.js#L48-L50] if you're looking for a reference implementation.

**Comment by hvadotnarola** [comment]
Actually i am using it with ionic (AngularJS 1).
How can i save that image after applying filter ?

**Comment by rendro** [comment]
Which version of vintageJS are you using?
